export default {
  name: 'blogPost',
  title: 'Blog Post',
  type: 'document',
  fields: [
    {
      name: 'publishedAt',
      type: 'datetime',
      title: 'Published At',
      description: 'When this blog post should go live',
      initialValue: () => new Date().toISOString(),
      validation: (Rule: any) => Rule.required(),
    },
    {name: 'title', type: 'string', title: 'Title'},
    {
      name: 'excerpt',
      title: 'Excerpt',
      type: 'text',
      rows: 2,
      validation: (Rule: any) =>
        Rule.max(160).warning('Excerpt should be 70 characters or fewer'),
    },
    {
      name: 'slug',
      type: 'slug',
      title: 'Slug',
      options: {source: 'title', maxLength: 96},
    },
    {
      name: 'featured',
      title: 'Featured',
      type: 'boolean',
      initialValue: false,
      description: 'Mark this post as featured to highlight it on the site',
    },
    {
      name: 'mainImage',
      type: 'image',
      title: 'Main Image',
      options: {hotspot: true},
    },
    {
      name: 'category',
      title: 'Category',
      type: 'reference',
      to: [{type: 'category'}],
    },
    {
      name: 'tags',
      type: 'array',
      title: 'Tags',
      of: [{type: 'string'}],
    },
    {
      name: 'body',
      title: 'Content',
      type: 'array',
      of: [
        {type: 'block'},
        {
          type: 'image',
        },
        {
          type: 'code',
          options: {
            withFilename: true,
            language: 'javascript', // default
            languageAlternatives: [
              {title: 'JavaScript', value: 'javascript'},
              {title: 'TypeScript', value: 'typescript'},
              {title: 'HTML', value: 'html'},
              {title: 'CSS', value: 'css'},
              {title: 'JSON', value: 'json'},
              {title: 'Shell', value: 'bash'},
              {title: 'Python', value: 'python'},
              {title: 'Java', value: 'java'},
              {title: 'Go', value: 'go'},
              {title: 'C', value: 'c'},
              {title: 'C++', value: 'cpp'},
              {title: 'C#', value: 'csharp'},
              {title: 'Rust', value: 'rust'},
              {title: 'Kotlin', value: 'kotlin'},
              {title: 'Swift', value: 'swift'},
              {title: 'Objective-C', value: 'objective-c'},
              {title: 'PHP', value: 'php'},
              {title: 'Ruby', value: 'ruby'},
              {title: 'R', value: 'r'},
              {title: 'Perl', value: 'perl'},
              {title: 'Scala', value: 'scala'},
              {title: 'Haskell', value: 'haskell'},
              {title: 'Lua', value: 'lua'},
              {title: 'Dart', value: 'dart'},
              {title: 'Elixir', value: 'elixir'},
              {title: 'Clojure', value: 'clojure'},
              {title: 'F#', value: 'fsharp'},
              {title: 'Visual Basic', value: 'visual-basic'},
              {title: 'Rust', value: 'rust'},
              {title: 'Solidity', value: 'solidity'},
              {title: 'Shell', value: 'shell'},
              {title: 'Bash', value: 'bash'},
              {title: 'PowerShell', value: 'powershell'},
            ],
          },
        },
      ],
    },
    {
      name: 'metaTitle',
      type: 'string',
      title: 'Meta Title',
      description: 'Used in browser tab and SEO title tag',
      validation: (Rule: any) =>
        Rule.max(60).warning('Meta title should be 60 characters or fewer'),
    },
    {
      name: 'metaDescription',
      type: 'text',
      title: 'Meta Description',
      description: 'Used in search engine results (max 160 characters)',
      validation: (Rule: any) =>
        Rule.max(160).warning('Meta description should be 160 characters or fewer'),
    },
  ],
}
